# Generated by Django 5.1 on 2024-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationreview',
            name='content_eng',
            field=models.TextField(null=True),
        ),
    ]
